alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  retention: 24h
  persistentVolume:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 64Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

extraScrapeConfigs: |
  - job_name: airflow-statsd
    static_configs:
      - targets:
          - airflow-statsd.airflow.svc.cluster.local:9102